module.exports = {
    category: [
        {
            name: 'Graphics',
            tags: [
                'VectorGraphics',
                'Viewer',
                '2DGraphics',
                '3DGraphics',
                'Photography',
                'RasterGraphics',
                'Graphics',
                'GUIDesigner',
            ],
        },
        {
            name: 'Games',
            tags: [
                'StrategyGame',
                'SportsGame',
                'Simulation',
                'Shooter',
                'Roleplaying',
                'RolePlaying',
                'Role Playing',
                'ActionGame',
                'Adventure',
                'LogicGame',
                'MMORPG',
                'KidsGame',
                'AdventureGame',
                'ArcadeGame',
                'BlocksGame',
                'BoardGame',
                'Amusement',
                'CardGame',
                'ConsoleOnly',
                'Emulator',
                'Fantasy',
                'Game',
                'Games',
            ],
        },
        {
            name: 'Audio',
            tags: [
                'Sequencer',
                'Player',
                'Audio',
                'Recorder',
                'Tuner',
                'AudioVideo',
                'HamRadio',
                'AudioVideoEditing',
                'Midi',
                'Music',
                'Mixer',
            ],
        },
        {
            name: 'Miscellaneous',
            tags: [
                'Security',
                'Application',
                'Art',
                'Core',
                'Documentation',
                'X-Tool',
                'GNOME',
                'Qt',
                'KDE',
                'GTK',
                'Profiling',
            ],
        },
        {
            name: 'Utility and Productivity',
            tags: [
                'System',
                'Settings',
                'PackageManager',
                'Maps',
                'Archiving',
                'Calculator',
                'TerminalEmulator',
                'Calendar',
                'Chart',
                'Productivity',
                'Clock',
                'ContactManagement',
                'DesktopSettings',
                'Utility',
                'Dictionary',
                'Email',
                'Feed',
                'FileManager',
                'FileTools',
                'HardwareSettings',
                'FileTransfer',
                'Monitor',
                'Filesystem',
            ],
        },
        {
            name: 'Science and Education',
            tags: [
                'Matrix',
                'Science',
                'Physics',
                'Math',
                'Astronomy',
                'Robotics',
                'Translation',
                'Chemistry',
                'Geoscience',
                'Education',
                'Electronics',
                'Literature',
                'LearnToCode',
                'Engineering',
                'Languages',
                'Geography',
                'MedicalSoftware',
            ],
        },
        {
            name: 'Internet and Communication',
            tags: [
                'RemoteAccess',
                'Network',
                'Chat',
                'P2P',
                'WebBrowser',
                'Web',
                'InstantMessaging',
                'IRCClient',
                'Internet',
                'Communication',
            ],
        },
        {
            name: 'Development',
            tags: [
                'DataVisualization',
                'Database',
                'Debugger',
                'WebDevelopment',
                'ProjectManagement',
                'IDE',
                'Java',
                'Development',
            ],
        },
        {
            name: 'Finance',
            tags: ['Finance', 'NumericalAnalysis', 'Economy'],
        },
        {
            name: 'Office',
            tags: [
                'Presentation',
                'News',
                'Scanning',
                'Telephony',
                'RevisionControl',
                'WordProcessor',
                'TextEditor',
                'Publishing',
                'OCR',
                'Office',
            ],
        },
        {
            name: 'Video',
            tags: ['TV', 'Video', 'VideoConference'],
        },
    ],
};
