module.exports = {
    category: {
        graphics: {
            name: 'graphics',
            tags: [
                'VectorGraphics',
                'Viewer',
                '2DGraphics',
                '3DGraphics',
                'Photography',
                'RasterGraphics',
                'Graphics',
                'GUIDesigner',
            ],
        },
        games: {
            name: 'games',
            tags: [
                'StrategyGame',
                'SportsGame',
                'Simulation',
                'Shooter',
                'Roleplaying',
                'RolePlaying',
                'Role Playing',
                'ActionGame',
                'Adventure',
                'LogicGame',
                'MMORPG',
                'KidsGame',
                'AdventureGame',
                'ArcadeGame',
                'BlocksGame',
                'BoardGame',
                'Amusement',
                'CardGame',
                'ConsoleOnly',
                'Emulator',
                'Fantasy',
                'Game',
                'Games',
            ],
        },
        audio: {
            name: 'audio',
            tags: [
                'Sequencer',
                'Player',
                'Audio',
                'Recorder',
                'Tuner',
                'AudioVideo',
                'HamRadio',
                'AudioVideoEditing',
                'Midi',
                'Music',
                'Mixer',
            ],
        },
        misc: {
            name: 'misc',
            tags: [
                'Security',
                'Application',
                'Art',
                'Core',
                'Documentation',
                'X-Tool',
                'GNOME',
                'Qt',
                'KDE',
                'GTK',
                'Profiling',
            ],
        },
        utility: {
            name: 'utility',
            tags: [
                'System',
                'Settings',
                'PackageManager',
                'Maps',
                'Archiving',
                'Calculator',
                'TerminalEmulator',
                'Calendar',
                'Chart',
                'Productivity',
                'Clock',
                'ContactManagement',
                'DesktopSettings',
                'Utility',
                'Dictionary',
                'Email',
                'Feed',
                'FileManager',
                'FileTools',
                'HardwareSettings',
                'FileTransfer',
                'Monitor',
                'Filesystem',
            ],
        },
        science: {
            name: 'science',
            tags: [
                'Matrix',
                'Science',
                'Physics',
                'Math',
                'Astronomy',
                'Robotics',
                'Translation',
                'Chemistry',
                'Geoscience',
                'Education',
                'Electronics',
                'Literature',
                'LearnToCode',
                'Engineering',
                'Languages',
                'Geography',
                'MedicalSoftware',
            ],
        },
        internet: {
            name: 'internet',
            tags: [
                'RemoteAccess',
                'Network',
                'Chat',
                'P2P',
                'WebBrowser',
                'Web',
                'InstantMessaging',
                'IRCClient',
                'Internet',
                'Communication',
            ],
        },
        development: {
            name: 'development',
            tags: [
                'DataVisualization',
                'Database',
                'Debugger',
                'WebDevelopment',
                'ProjectManagement',
                'IDE',
                'Java',
                'Development',
            ],
        },
        finance: {
            name: 'finance',
            tags: ['Finance', 'NumericalAnalysis', 'Economy'],
        },
        office: {
            name: 'office',
            tags: [
                'Presentation',
                'News',
                'Scanning',
                'Telephony',
                'RevisionControl',
                'WordProcessor',
                'TextEditor',
                'Publishing',
                'OCR',
                'Office',
            ],
        },
        video: {
            name: 'video',
            tags: ['TV', 'Video', 'VideoConference'],
        },
    },
};
