blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/app-outlet/app-outlet/discussions
    about: For questions, suggestions or support please see out discussions section
